### ISSUE TITLE
User additional attributes are not applied

### ISSUE THREAD

**Issue by mohitmutha** [keycloak/keycloak-realm-operator#21]
### Describe the bug

Create a realm with users and an additional attribute `customer` as below
The realm is applied but the additional attribute is not applied to the created user
```
...
users:
      - username: eot-user
        enabled: true
        emailVerified: true
        firstName: EOT
        lastName: User
        email: eot-user@eot.com
        attributes:
          customer:
            - "TST"
        credentials:
        - type: password
          value: admin
        realmRoles:
        - default-roles-eot
        requiredActions:
        - UPDATE_PASSWORD
        groups:
        - "/device-management/devices-read"
```

### Version

24.0.3

### Expected behavior

The additional attribute should be mapped to the user

### Actual behavior

Attribute is not mapped
