### ISSUE TITLE
KeycloakUser CR - password portion is not stored in secret

### ISSUE THREAD

**Issue by nuwang** [keycloak/keycloak-realm-operator#6]
### Describe the bug

When a KeycloakUser CR is created, the corresponding user is created in keycloak. However, the generated user password is not stored in the secret. Only the username is. It appears that the secret is first created with the username, and a subsequent, independent effort is made to store the password. However, this results in a "secret already exists" exception.

### Version

Keycloak version: 20.0.1
Realm operator version: 1.0.0 (also tested with main branch)

### Expected behavior

The existing secret is updated with the password, instead of attempting to create a new secret.

### Actual behavior

Fails to update secret with new password, only the username is stored.

### How to Reproduce?

The following CR:
```yaml
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: mytestuser
  namespace: keycloak
  labels:
    app: keycloak-sso
spec:
  realmSelector:
    matchLabels:
      app: keycloak-sso
  user:
    username: "myuser"
    firstName: "test"
    lastName: "test"
    email: "helloworld@test.com"
    enabled: True
```

results in the following secret:
```yaml
apiVersion: v1
data:
  username: bXl1c2Vy
kind: Secret
metadata:
  name: credential-myrealm-myuser-keycloak
  namespace: keycloak
  ownerReferences:
  - apiVersion: legacy.k8s.keycloak.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KeycloakUser
    name: mytestuser
    uid: 3e347cb7-6acd-4e66-9e8b-b0db9b3d0714
  resourceVersion: "20023289"
  uid: 148dd42b-f742-4a04-8531-6fbf84b430b9
type: Opaque
```

### Anything else?

Operator logs:
```
{"level":"info","ts":1668318264.9262962,"logger":"controller_keycloakuser","msg":"Reconciling KeycloakUser","Request.Namespace":"keycloak","Request.Name":"mytestuser"}
{"level":"info","ts":1668318264.926366,"logger":"controller_keycloakuser","msg":"found 1 matching realm(s) for user keycloak/mytestuser"}
I1113 05:44:24.931312       1 request.go:655] Throttling request took 1.047751379s, request: GET:https://10.100.0.1:443/apis/batch/v1beta1?timeout=32s
{"level":"info","ts":1668318264.9428363,"logger":"action_runner","msg":"found keycloak url: https://mykeycloak-service:8443"}
{"level":"info","ts":1668318265.0072143,"logger":"controller_keycloakuser","msg":"read state for keycloak keycloak/external-keycloak, realm keycloak/myrealm"}
{"level":"info","ts":1668318265.0407786,"logger":"action_runner","msg":"(    0)    SUCCESS check if keycloak is available"}
{"level":"info","ts":1668318265.049523,"logger":"action_runner","msg":"(    1)    SUCCESS update user myuser"}
{"level":"info","ts":1668318265.0603938,"logger":"action_runner","msg":"(    2)     FAILED create credential secret for user myuser in realm keycloak/myrealm : secrets \"credential-myrealm-myuser-keycloak\" already exists"}
```

It would also be great if the operator could reuse an existing secret, instead of always creating a new one, which would come in handy with git-ops/sealed-secret managed secrets and make the operator more similar to how other operators work. The vault mechanism is too specialised and has its own learning curve.
