### ISSUE TITLE
Vault secrets not being replaced

### ISSUE THREAD

**Issue by nuwang** [keycloak/keycloak-realm-operator#8]
### Describe the bug

I attempted to create a KeycloakClient CR and a KeycloakUser CR with secrets read from the vault. My understanding was that the vault reference would be replaced with the contents of the file mounted at the designated location. In both cases, the secrets were stored literally, instead of being read from the vault.

The keycloak secrets appear to be mounted at the expected path in the container, and I believe, follow the required naming convention.

### Version

Keycloak operator: 20.0.1, Realm operator: 1.0.0

### Expected behavior

Secret `'${vault.myclientsecret}'` is replaced by the secret from the filesystem path.

### Actual behavior

Secret is stored as a literal string: `'${vault.myclientsecret}'`.

### How to Reproduce?

The keycloak CR looks as follows:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: mykeycloak
  namespace: keycloak
spec:
  ...
  additionalOptions:
    - name: vault
      value: file
    - name: vault-dir
      value: /opt/keycloak/secrets
    - name: spi-vault-file-key-resolvers
      value: REALM_UNDERSCORE_KEY
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - name: vault
                mountPath: /opt/keycloak/secrets
        volumes:
          - name: vault
            secret:
              secretName: keycloak-vault

```
I verified that the secrets were mounted in the container.

The client CR:
```yaml
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: myclient
  namespace: keycloak
spec:
  client:
    ...
    secret: '${vault.myclientsecret}'
```

### Anything else?

I'm assuming the vault extension is enabled by default in the keycloak 20.0.1 operator. Is there a way to check?

```bash

$ /opt/keycloak/bin/kc.sh show-config

Current Mode: production
Current Configuration:
	kc.cache =  ispn (KcEnvVarConfigSource)
        ...
	kc.spi.vault.file.key.resolvers =  REALM_UNDERSCORE_KEY (KcEnvVarConfigSource)
	kc.vault =  file (KcEnvVarConfigSource)
	kc.vault-dir =  /opt/keycloak/secrets (KcEnvVarConfigSource)
	kc.vault.dir =  /opt/keycloak/secrets (KcEnvVarConfigSource)
	kc.version =  20.0.1 (SysPropConfigSource)
```
